spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb_test:3306/testdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate